stages:
  - build
  - test
  - publish
  - deploy

default:
  image: openjdk:15
  before_script:
    - chmod +x ./gradlew
  cache:
    key: apus-gradle-cache
    paths:
      - .gradle

.prod:
  only:
    refs:
      - main

deployServer:
  image: docker:20
  before_script:
    - cd config
  script:
    - docker-compose up -d
  extends:
    - .prod

include:
  - local: config/ci/database-ci.yml
  - local: config/ci/client-ci.yml
  - local: config/ci/server-ci.yml