create-database-image:
  stage: dockerize
  image: docker:20
  before_script:
    - cd database
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
    - docker build -t registry.gitlab.com/kiliankra/apus/database:latest .
    - docker tag registry.gitlab.com/kiliankra/apus/database:latest registry.gitlab.com/kiliankra/apus/database:${CI_COMMIT_SHORT_SHA}
    - docker push registry.gitlab.com/kiliankra/apus/database:latest
    - docker push registry.gitlab.com/kiliankra/apus/database:${CI_COMMIT_SHORT_SHA}
  extends:
    - .prod
